Scale/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

app_name='item'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('dashboard/', include("dashboard.urls")),
    path("items/", include("item.urls")),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.shortcuts import render
from .forms import LoginForm
from . import views


app_name ='core'

urlpatterns =[
    path("", views.index, name="index"),
    path("signup/", views.signup , name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="core/login.html", authentication_form = LoginForm), name="login"),
    path("logout/", views.logout_view, name="logout")
] 

dashboard/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.shortcuts import render
from . import views

app_name ='dashboard'

urlpatterns =[
    path("/dashboard", views.index, name="index"),
] 

item/urls.py
from django.urls import path
from . import views

app_name = 'item'


urlpatterns = [
    path('', views.browse, name="browse"),
    path("<int:pk>/", views.details, name="details"),
    path("<int:pk>", views.category, name="category"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/edit/", views.edit, name="edit"),
    path("additem/", views.new, name="new")
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Your username",
        'class': "mx-2 my-2 px-2 py-2 rounded-xl"
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': "Your password",
        'class': "mx-2 my-2 px-2 py-2 rounded-xl"
    }))

class SignUpForm(UserCreationForm):
    class Meta():
        model = User
        fields = ('username', 'email', 'password1', 'password2')
   
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Your username",
        'class': "mx-2 my-2 px-3 py-3 rounded-xl"
        
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': "Your email address",
        'class': "mx-2 my-2 px-2 py-2 rounded-xl"
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': "Your password",
        'class': "mx-2 my-2 px-2 py-2 rounded-xl"
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': "Repeat password",
        'class': "mx-2 my-2 px-2 py-2 rounded-xl"
    }))

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from item.models import *
from .forms import *

# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    
    return render(request, "core/index.html",{
        "items":items,
        "categories":categories
    })


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)

        if form.is_valid:
          form.save()

          return redirect('/login/')
        
    else:    
        form = SignUpForm

    return render(request, "core/signup.html",{
        "form":form
    }) 

def logout_view(request):
    logout(request)
    return redirect('/login/') 
 

core/templates/core/index.html
{% extends "core/layout.html" %}

{% block title %} Welcome | Scale {% endblock %}

{% block body %}
<div class="mt-6 px-6 py-12 rounded-xl bg-gray-100">
    <h3 class="mb-12 text-2xl text-center">Categories</h3>

        <div class="grid grid-cols-3 gap-3">
        {% for category in categories %}
            <div class="bg-white rounded-xl">
                <a href="{% url 'item:category' category.id %}">
                    <div>
                        <img src="{{ category.image.url }}" class="rounded-t-xl">
                    </div>
                    <div>
                        <p class="text-lg text-gray-700">Category : {{category.name}}</p>
                        <p class="text-lg text-gray-700 rounded-b-xl"> items : {{category.items.count}}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
        </div>
</div>

<div class="mt-6 px-6 py-12 rounded-xl bg-gray-100">
    <h3 class="mb-12 text-2xl text-center">Newest Items</h3>

        <div class="grid grid-cols-3 gap-3">
        {% for item in items %}
            <div class="bg-white rounded-xl">
                <a href="{% url 'item:details' item.id %}">
                    <div>
                    <img src="{{ item.image.url }}" class="rounded-t-xl">
                    </div>

                    <div>
                        <p class="text-lg text-gray-700">Name : {{item.itemname}}</p>
                        <p class="text-lg text-gray-700 rounded-b-xl"> Price : Rs.{{item.price}}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
        </div>
</div>





{% endblock %}

core/templates/core/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device=width, initial-scale=1.0">
        <title>{% block title %} {% endblock %}</title>
        <style>
            body {
                background-color: white;
            }

        </style>

        <script src="https://cdn.tailwindcss.com"></script>
    </head>    
    <body>
        <nav class="px-6 py-6 flex justify-between items-center border-b border-gray-200">
            <a href="{% url 'core:index' %}" class="text-xl font-semibold">Scale</a>
            <div class="space-x-6">
                <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New Item</a>
                <a href="{% url 'item:browse' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>
                {% if request.user.is_authenticated %}
                <a href="{% url 'core:logout' %}" class="text-lg font-semibold hover:text-gray-500">Logout</a>
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 rounded-xl text-white">Inbox</a>
                <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 rounded-xl text-white">Dashboard</a>                
                {% else %}
                 <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 rounded-xl text-white">Login</a>
                 <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 rounded-xl text-white">Sign up</a>
                {% endif %}
            </div>
        </nav>


        <div class="px-6 py-6">
        {% block body %}
        {% endblock %}
        </div>
        <footer class="px-6 py-6 flex justify-between bg-gray-800">
            <div class="pr-10 w-2/3">
            <h3 class="text-teal-600 text-lg font-semibold">About</h3>
            <p class="text-teal-600 text-lg font-semibold">afnjejfjfb fueauf ueuf uaf ueuf</p>
            </div>

            <div class="w-1/3 mb-15 space-y-2">
                <h3 class="text-teal-500 font-semibold">Menu</h3>
                <ul>
                <li><a href="#" class="text-teal-500 hover:text-gray-700 font-semibold"">Contact</a></li>
                <li><a href="#" class="text-teal-500 hover:text-gray-700 font-semibold">About</a></li>
                <li><a href="#" class="text-teal-500 hover:text-gray-700 font-semibold">Privacy</a></li>
                <li><a href="#" class="text-teal-500 hover:text-gray-700 font-semibold">Terms of use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html

core/templates/core/login.html
{% extends "core/layout.html" %}


{% block title %}Login in{% endblock %}

{% block body %}
<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl border-b">
    <h1 class="text-xl font-semibold text-center text-gray-700">Login</h1>
    <form action="." method="post">
        {% csrf_token %}
        
       

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label>
            {{ form.password }}
        </div>


        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl">Submit</button>
    </form>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends "core/layout.html" %}


{% block title %}SignUP{% endblock %}

{% block body %}
<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl border-b">
    <h1 class="text-xl font-semibold text-center text-gray-700">Sign Up</h1>
    <form action="." method="post">
        {% csrf_token %}
        
       

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email Address</label>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat Password</label>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl">Submit</button>
    </form>
</div>
{% endblock %}