Scale/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

app_name='item'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('dashboard/', include("dashboard.urls")),
    path("items/", include("item.urls")),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.shortcuts import render
from .forms import LoginForm
from . import views


app_name ='core'

urlpatterns =[
    path("", views.index, name="index"),
    path("signup/", views.signup , name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="core/login.html", authentication_form = LoginForm), name="login"),
    path("logout/", views.logout_view, name="logout")
] 

item/urls.py
from django.urls import path
from . import views

app_name = 'item'


urlpatterns = [
    path('', views.browse, name="browse"),
    path("<int:pk>/", views.details, name="details"),
    path("<int:pk>", views.category, name="category"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/edit/", views.edit, name="edit"),
    path("additem/", views.new, name="new")
]

item/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=64)
    image = models.ImageField(upload_to="category_imagesScalae", null=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = "Categories"

    def __str__(self):
        return f"{self.name}"    
    
class Item(models.Model):
    category = models.ForeignKey(Category, related_name="items", on_delete=models.CASCADE)
    itemname = models.CharField(max_length=64)
    description = models.TextField(blank=True, null=True)
    manufacturer = models.CharField(max_length = 64)
    price = models.IntegerField()
    image = models.ImageField(upload_to="item_images", null=True)
    is_sold = models.BooleanField(default = False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.category}|{self.itemname} by {self.manufacturer} : Rs. {self.price} "

item/forms.py
from django import forms

from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'
class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'itemname', 'description', 'manufacturer', 'price', 'image')

        widgets = {
            'category':forms.Select(attrs={
                'class':'w-full py-4 px-6 rounded-xl border'
            })
        }

        widgets = {
            'itemname':forms.TextInput(attrs={
                'class':'w-full py-4 px-6 rounded-xl border'
            })
        }

        widgets = {
            'description':forms.Textarea(attrs={
                'class':'w-full py-4 px-6 rounded-xl border'
            })
        }
        widgets = {
            'manufacturer':forms.TextInput(attrs={
                'class':'w-full py-4 px-6 rounded-xl border'
            })
        }   
        widgets = {
            'price':forms.TextInput(attrs={
                'class':'w-full py-4 px-6 rounded-xl border'
            })
        }   
        widgets = {
            'image':forms.FileInput(attrs={
                'class':'w-full py-4 px-6 rounded-xl border'
            })
        }   

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('itemname', 'description', 'manufacturer', 'price', 'image', 'is_sold')

        widgets = {
            'itemname':forms.TextInput(attrs={
                'class':'w-full py-4 px-6 rounded-xl border'
            })
        }

        widgets = {
            'description':forms.Textarea(attrs={
                'class':'w-full py-4 px-6 rounded-xl border'
            })
        }
        widgets = {
            'manufacturer':forms.TextInput(attrs={
                'class':'w-full py-4 px-6 rounded-xl border'
            })
        }   
        widgets = {
            'price':forms.TextInput(attrs={
                'class':'w-full py-4 px-6 rounded-xl border'
            })
        }   
        widgets = {
            'image':forms.FileInput(attrs={
                'class':'w-full py-4 px-6 rounded-xl border'
            })
        }                   

item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
# Create your views here.

def browse(request):
    query = request.GET.get('query','')
    items = Item.objects.filter(is_sold=False)
    if query:
        items=items.filter(itemname__icontains=query)

    return render(request, 'item/browse.html',{                          
    'items':items,
    'query':query,
    })

def details(request, pk):
    item = get_object_or_404(Item, pk=pk)

    return render(request, "item/detail.html",{
        "item":item
    })

def category(request, pk):
    category = get_object_or_404(Category, pk=pk)

    return render(request, "item/category.html",{
        "category":category,
        "items":category.items.all()
    })

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid:
            item=form.save(commit=False)
            item.created_by = request.user
            item.save()
        
            return redirect('item:details', pk=item.id)    
    else:
        form = NewItemForm()

    return render(request, "item/form.html",{
        'form':form
    } )

@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by = request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid:
            item.save()
        
            return redirect('item:details', pk=item.id)    
    else:
        form = EditItemForm(instance=item)

    return render(request, "item/form.html",{
        'form':form
    } )
                             

item/templates/item/browse.html
{% extends 'core/layout.html' %}

{% block title %}Browse{% endblock %}

{% block body %}

    <div class="mt-6 px-6 py-12 rounded-xl bg-gray-100">
            <div class="grid grid-cols-4 gap-3">
                <div class="cols-span-1">
                <form method="get" action="{% url 'item:browse' %}">
                    <input name="query" class="w-full py-4 px-6 rounded-xl" type="text" value="{{ query }}" placeholder="Search any item">
                    <button class="inline-block px-8 py-4 mb-6 mt-6 bg-teal-500 text-lg text-white font-semibold">Search</button>
                </form>
                </div>
            {% for item in items %}
                <div class="bg-white rounded-xl">
                    <a href="{% url 'item:details' item.id %}">
                        <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>
    
                        <div>
                            <p class="text-lg text-gray-700">Name : {{item.itemname}}</p>
                            <p class="text-lg text-gray-700 rounded-b-xl"> Price : Rs.{{item.price}}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
            </div>
    </div>

{% endblock %}

item/templates/item/category.html
{% extends "core/layout.html" %}

{% block title %}{{category.name}}{% endblock %}

{% block body %}
<h1 class="text-xl font-semibold text-center text-gray-700">Category | {{category.name}}</h1>
<div class="mt-6 px-6 py-12 rounded-xl bg-gray-100">
    <div class="grid grid-cols-3 gap-3">
        {% for item in items %}
            
                <div class="bg-white rounded-xl">
                    <a href="{% url 'item:details' item.id %}">
                        <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>
    
                        <div>
                            <p class="text-lg text-gray-700">Name : {{item.itemname}}</p>
                            <p class="text-lg text-gray-700 rounded-b-xl"> Price : Rs.{{item.price}}</p>
                        </div>
                    </a>
                </div>
            
        {% endfor %}
    </div>
</div>
{% endblock %}

item/templates/item/detail.html
{% extends "core/layout.html" %}

{% block title %} {{item.itemname}} {% endblock %}

{% block body %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-2">
        <img src="{{ item.image.url }}" class="rounded-xl bg-gray-200">
    </div>
    
    <div class="col-span-3 px-3 bg-gray-100 space-y-2 rounded-xl">
        <ul>
            <li><h1 class="text-center text-xl rounded-xl text-gray-700 bg-gray-200 py-6">{{item.itemname}}</h1></li>
            <li><p class="text-lg text-gray-700">Created by :{{item.manufacturer}}</p></li>
            <li><p class="text-lg text-gray-700">Price :{{item.price}}</p></li>
            <li><p class="text-lg text-gray-700">Sold: {{item.is_sold}}</p></li>
            <li><p class="text-lg my-4 text-gray-700 bg-white rounded-xl">Description:<br>{{item.description}}</p></li>
            <div class="space-y-3">
                {% if request.user == item.created_by %}
                    <a href="{% url 'item:edit' item.id %}" class="px-3 py-4 text-white bg-teal-500 rounded-xl text-xl">Edit</a>
                    <a href="{% url 'item:delete' item.id %}" class="px-3 py-4 text-white bg-red-500 rounded-xl text-xl">Delete</a>
                {% else %}
                    <a href="#" class="px-3 py-4 text-white bg-teal-500 rounded-xl text-xl">Contact seller</a>
                {% endif %}
            </div>
        </ul>
    </div>


</div>
{% endblock %}

item/templates/item/form.html
{% extends "core/layout.html" %}

{% block title %}Add Item{% endblock %}

{% block body %}
<div class="mb-6 bg-gray-200 rounded-xl">
    <h1 class="text-xl font-semibold bg-gray-200 rounded-xl">Add Item</h1>
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        <div class="space-y-6">
            {{form.as_p}}
        </div> 
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl">Submit</button>
</div>
{% endblock %}